export enum QueryKeys {
  MODERATION_VIEW = 'MODERATION_VIEW',
  NEWS_LIST = 'NEWS_LIST',
  NEWS_VIEW = 'NEWS_VIEW',
  ORDER_VIEW = 'ORDER_VIEW',
  PRODUCT_CATEGORIES = 'PRODUCT_CATEGORIES',
  PRODUCT_VIEW = 'PRODUCT_VIEW',
  PROFILE = 'PROFILE',
  SERVICE_CATEGORIES = 'SERVICE_CATEGORIES',
  SERVICE_LIST = 'SERVICE_LIST',
  USER_VIEW = 'USER_VIEW',
}
